version: '3.8'

services:
  erthsobesservis:
    image: erthsobes/erthsobesservis
    ports:
      - "6500:6500"
  erthsobesdb:
    image: erthsobes/erthsobes-db
    environment:  
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=orders
      - POSTGRES_DB=orders
    ports:
      - "5432:5432"